FROM registry.cn-hangzhou.aliyuncs.com/raincloud/spbootdocker:v1-openjdk

# ADD target/xxl-job-admin-*.jar /app.jar
ADD http://dockers-files.oss-cn-hangzhou.aliyuncs.com/xxl-job/xxl-job-admin-2.1.0-SNAPSHOT.jar /app.jar

